apiVersion: v1
kind: Pod
metadata:
  name: sess-no-gpu
  labels:
    home-afs: "true" 
    mount-eos: "true" 
    mount-cvmfs: "true" 
    mount-afs: "true" 
spec:
  containers:
  - name: container
    image: registry.cern.ch/ngt/lxplus-like:9 
    command: ["/usr/bin/tini", "--", "sleep", "infinity"]
