# Complete Configuration Changes for Pseudorapidity + Inverse pT + Multi-Layer Regression

## 1. DATA SECTION - Add eta to inputs
# Location: data.inputs.hit (around line 25-50)

data:
  inputs:
    hit:
      # Global hit coordinates
      - spacePoint_globEdgeHighX
      - spacePoint_globEdgeHighY
      - spacePoint_globEdgeHighZ
      - spacePoint_globEdgeLowX
      - spacePoint_globEdgeLowY
      - spacePoint_globEdgeLowZ
      - spacePoint_time
      - spacePoint_driftR
      # Add covariance information
      - spacePoint_covXX
      - spacePoint_covXY
      - spacePoint_covYX
      - spacePoint_covYY
      # Add detector information
      - spacePoint_channel
      - spacePoint_layer
      - spacePoint_stationPhi
      - spacePoint_stationEta
      - spacePoint_stationIndex
      - spacePoint_technology
      # Add derived hit fields
      - r  # Radial distance
      - s  # 3D distance
      - theta  # Polar angle
      - phi  # Azimuthal angle
      - eta  # ← ADD THIS LINE: Pseudorapidity

## 2. INPUT NET SECTION - Update input_size from 22 to 23
# Location: model.model.init_args.input_nets (around line 165)

                net:
                  class_path: hepattn.models.Dense
                  init_args:
                    input_size: 23  # ← CHANGE from 22 to 23
                    output_size: *dim

## 3. INPUT NET FIELDS - Add eta to fields list
# Location: model.model.init_args.input_nets (around line 145-170)

            - class_path: hepattn.models.InputNet
              init_args:
                input_name: hit
                fields:
                  # Global hit coordinates
                  - spacePoint_globEdgeHighX
                  - spacePoint_globEdgeHighY
                  - spacePoint_globEdgeHighZ
                  - spacePoint_globEdgeLowX
                  - spacePoint_globEdgeLowY
                  - spacePoint_globEdgeLowZ
                  - spacePoint_time
                  - spacePoint_driftR
                  # Add covariance information
                  - spacePoint_covXX
                  - spacePoint_covXY
                  - spacePoint_covYX
                  - spacePoint_covYY
                  # Add detector information
                  - spacePoint_channel
                  - spacePoint_layer
                  - spacePoint_stationPhi
                  - spacePoint_stationEta
                  - spacePoint_technology
                  - spacePoint_stationIndex
                  # Add derived hit fields
                  - r  # Radial distance
                  - s  # 3D distance
                  - theta  # Polar angle
                  - phi  # Azimuthal angle
                  - eta  # ← ADD THIS LINE: Pseudorapidity

## 4. POSENC SECTION - Optionally add eta to position encoding
# Location: model.model.init_args.input_nets.posenc (around line 185)
# NOTE: This is optional - only if you want eta in position encoding

                posenc:
                  class_path: hepattn.models.posenc.PositionEncoder
                  init_args:
                    input_name: hit
                    dim: *dim
                    fields:
                      - r
                      - theta
                      - phi
                      - eta  # ← OPTIONAL: Add eta to position encoding
                    dim: *dim
                    sym_fields:
                      - phi

## 5. REGRESSION TASK - Replace ObjectRegressionTask
# Location: model.model.init_args.tasks (around line 271)

            - class_path: hepattn.models.task.WeightedPoolingObjectHitRegressionTask
              init_args:
                name: parameter_regression
                input_hit: hit
                input_object: query
                output_object: track
                target_object: particle
                hit_fields:
                  - spacePoint_globEdgeHighX
                  - spacePoint_globEdgeHighY
                  - spacePoint_globEdgeHighZ
                  - spacePoint_globEdgeLowX
                  - spacePoint_globEdgeLowY
                  - spacePoint_globEdgeLowZ
                  - spacePoint_time
                  - spacePoint_driftR
                  - spacePoint_covXX
                  - spacePoint_covXY
                  - spacePoint_covYX
                  - spacePoint_covYY
                  - spacePoint_channel
                  - spacePoint_layer
                  - spacePoint_stationPhi
                  - spacePoint_stationEta
                  - spacePoint_stationIndex
                  - spacePoint_technology
                  - r
                  - s
                  - theta
                  - phi
                  - eta  # Pseudorapidity (23rd feature)
                fields:
                  - truthMuon_eta
                  - truthMuon_phi
                  - truthMuon_pt
                  - truthMuon_q
                inverse_fields:
                  - truthMuon_pt  # Regress as 1/pT
                loss_weight: 1.0
                dim: *dim
                assignment_threshold: 0.1
                # Multi-layer regression head parameters
                regression_hidden_dim: 144
                regression_num_layers: 3
                dropout: 0.1

## SUMMARY OF CHANGES:

✅ 1. Add `eta` to `data.inputs.hit` list
✅ 2. Update `input_size: 23` in InputNet (was 22)
✅ 3. Add `eta` to InputNet `fields` list
✅ 4. (Optional) Add `eta` to position encoding fields
✅ 5. Add `eta` to regression task `hit_fields` (already done in snippet)
✅ 6. Add `inverse_fields: [truthMuon_pt]` for 1/pT regression
✅ 7. Add multi-layer regression head parameters

## NOTE: 
The `eta` feature is automatically computed in `data.py` from theta:
```python
hits["eta"] = -np.log(np.tan(hits["theta"] / 2.0))
```

So you just need to list it in the config - no need to modify data preprocessing further.
