# lightning.pytorch==2.5.1.post0
seed_everything: 42
trainer:
  accelerator: gpu
  strategy: auto
  devices:
  - 3
  num_nodes: 1
  precision: bf16-mixed
  logger:
    class_path: lightning.pytorch.loggers.CometLogger
    init_args:
      api_key: null
      workspace: null
      project: atlas_muon_filtering
      experiment_key: null
      mode: null
      online: null
      prefix: null
  callbacks:
  - class_path: hepattn.callbacks.Compile
  - class_path: hepattn.callbacks.InferenceTimer
  - class_path: hepattn.callbacks.SaveConfig
  - class_path: hepattn.callbacks.Checkpoint
    init_args:
      monitor: val/acc
      save_top_k: 1
      dirpath: null
      verbose: false
      save_last: null
      save_weights_only: false
      mode: max
      every_n_train_steps: null
      train_time_interval: null
      every_n_epochs: null
      save_on_train_epoch_end: null
      enable_version_counter: true
  - class_path: hepattn.callbacks.PredictionWriter
    init_args:
      write_inputs: false
      write_outputs: false
      write_preds: true
      write_targets: false
      write_losses: false
      write_layers: null
  - class_path: lightning.pytorch.callbacks.LearningRateMonitor
    init_args:
      logging_interval: null
      log_momentum: false
      log_weight_decay: false
  - class_path: lightning.pytorch.callbacks.TQDMProgressBar
    init_args:
      refresh_rate: 50
      process_position: 0
      leave: false
  - class_path: lightning.pytorch.callbacks.EarlyStopping
    init_args:
      monitor: val/acc
      min_delta: 0.0
      patience: 15
      verbose: true
      mode: max
      strict: true
      check_finite: true
      stopping_threshold: null
      divergence_threshold: null
      check_on_train_epoch_end: null
      log_rank_zero_only: false
  fast_dev_run: false
  max_epochs: 50
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: 50
  enable_checkpointing: null
  enable_progress_bar: true
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: logs
  model_registry: null
model:
  model:
    class_path: hepattn.models.HitFilter
    init_args:
      input_nets:
        class_path: torch.nn.ModuleList
        init_args:
          modules:
          - class_path: hepattn.models.InputNet
            init_args:
              input_name: hit
              net:
                class_path: hepattn.models.Dense
                init_args:
                  input_size: 21
                  output_size: 256
                  hidden_layers: null
                  hidden_dim_scale: 2
                  activation: null
                  final_activation: null
                  dropout: 0.0
                  bias: true
                  norm_input: true
              fields:
              - spacePoint_globEdgeHighX
              - spacePoint_globEdgeHighY
              - spacePoint_globEdgeHighZ
              - spacePoint_globEdgeLowX
              - spacePoint_globEdgeLowY
              - spacePoint_globEdgeLowZ
              - spacePoint_time
              - spacePoint_driftR
              - spacePoint_covXX
              - spacePoint_covXY
              - spacePoint_covYX
              - spacePoint_covYY
              - spacePoint_channel
              - spacePoint_layer
              - spacePoint_stationPhi
              - spacePoint_stationEta
              - spacePoint_technology
              - r
              - s
              - theta
              - phi
              posenc:
                class_path: hepattn.models.FourierPositionEncoder
                init_args:
                  input_name: hit
                  dim: 256
                  fields:
                  - phi
                  scale: 0.1
      encoder:
        class_path: hepattn.models.Encoder
        init_args:
          num_layers: 8
          dim: 256
          attn_type: flash
          window_size: 512
          window_wrap: true
          score_mod: null
          value_residual: false
          attn_kwargs: null
          norm: RMSNorm
          layer_scale: null
          drop_path: 0.0
          hybrid_norm: true
          dense_kwargs: null
      tasks:
        class_path: torch.nn.ModuleList
        init_args:
          modules:
          - class_path: hepattn.models.task.HitFilterTask
            init_args:
              name: hit_filter
              input_object: hit
              target_field: on_valid_particle
              dim: 256
              threshold: 0.1
              mask_keys: false
              loss_fn: bce
      input_sort_field: phi
  lrs_config:
    initial: 1.0e-05
    max: 3.0e-05
    end: 1.0e-06
    pct_start: 0.05
    weight_decay: 1.0e-05
  optimizer: Lion
data:
  train_dir: /home/iwsatlas1/jrenusch/master_thesis/tracking/data/root/train_PU200_processed
  val_dir: /home/iwsatlas1/jrenusch/master_thesis/tracking/data/root/valid_PU200_processed
  num_workers: 10
  num_train: -1
  num_val: -1
  num_test: -1
  batch_size: 1
  test_dir: null
  pin_memory: true
  use_smart_batching: false
  drop_last: false
  max_hits_per_batch: 50000
  inputs:
    hit:
    - spacePoint_globEdgeHighX
    - spacePoint_globEdgeHighY
    - spacePoint_globEdgeHighZ
    - spacePoint_globEdgeLowX
    - spacePoint_globEdgeLowY
    - spacePoint_globEdgeLowZ
    - spacePoint_time
    - spacePoint_driftR
    - spacePoint_covXX
    - spacePoint_covXY
    - spacePoint_covYX
    - spacePoint_covYY
    - spacePoint_channel
    - spacePoint_layer
    - spacePoint_stationPhi
    - spacePoint_stationEta
    - spacePoint_technology
    - r
    - s
    - theta
    - phi
  targets:
    hit:
    - on_valid_particle
  event_max_num_particles: 6
name: ATLAS-Muon-v1
optimizer: null
lr_scheduler: null
return_predictions: null
ckpt_path: /master_thesis/tracking/hepattn_muon/logs/ATLAS-Muon-v1_20250814-T223545/ckpts/epoch=014-val_acc=0.99418.ckpt
