baseline_filtering_stats:
  baseline_tracks: 0
  rejected_tracks: 10
  total_tracks: 10
data_directory: /scratch/ml_test_data_156000_hdf5_filtered_wp0990_maxtrk2_maxhit500
evaluation_file: /eos/project/e/end-to-end-muon-tracking/tracking/data/best2tracktracking/TRK-ATLAS-Muon-smallModel_20250915-T192111/ckpts/epoch=008-val_loss=1.62751_ml_test_data_156000_hdf5_filtered_wp0990_maxtrk2_maxhit500_eval.h5
evaluation_timestamp: '2025-09-19 16:35:11'
max_events: 5
results_by_region:
  all_tracks:
    task1_hit_track_assignment:
      average_efficiency: 0.2293029595015576
      average_fake_rate: 0.04010217511423884
      efficiency_std: 0.40038722804087085
      fake_rate_std: 0.09957124931218772
      roc_auc: 0.9224092371323529
      total_hits: 912
      true_assignments: 272
    task2_track_validity:
      average_efficiency: 0.25
      average_fake_rate: 0.0
      efficiency_std: 0.4330127018922193
      fake_rate_std: 0.0
      roc_auc: .nan
      total_tracks: 10
      valid_tracks: 10
    task3_regression:
      eta:
        mean_residual: .nan
        n_predictions: 0
        outliers_removed: 10
        std_residual: .nan
      phi:
        mean_residual: .nan
        n_predictions: 0
        outliers_removed: 10
        std_residual: .nan
      qpt:
        mean_residual: -0.045867919921875
        n_predictions: 10
        outliers_removed: 0
        std_residual: 0.05828857421875
  baseline_filtered: {}
  rejected_tracks:
    task2_track_validity:
      average_efficiency: 0.25
      average_fake_rate: 0.0
      efficiency_std: 0.4330127018922193
      fake_rate_std: 0.0
      roc_auc: .nan
      total_tracks: 10
      valid_tracks: 10
