baseline_filtering_stats:
  baseline_tracks: 0
  rejected_tracks: 193
  total_tracks: 193
data_directory: /scratch/ml_test_data_156000_hdf5_filtered_wp0990_maxtrk2_maxhit500
evaluation_file: /eos/project/e/end-to-end-muon-tracking/tracking/data/best2tracktracking/TRK-ATLAS-Muon-smallModel_20250915-T192111/ckpts/epoch=008-val_loss=1.62751_ml_test_data_156000_hdf5_filtered_wp0990_maxtrk2_maxhit500_eval.h5
evaluation_timestamp: '2025-09-19 16:41:13'
max_events: 1000
results_by_region:
  all_tracks:
    task1_hit_track_assignment:
      average_efficiency: 0.7427831290144056
      average_fake_rate: 0.13257830200525747
      efficiency_std: 0.376924652623221
      fake_rate_std: 0.10315758443270957
      roc_auc: 0.9357511780040084
      total_hits: 16065
      true_assignments: 5259
    task2_track_validity:
      average_efficiency: 0.8
      average_fake_rate: 0.0
      efficiency_std: 0.4
      fake_rate_std: 0.0
      roc_auc: .nan
      total_tracks: 193
      valid_tracks: 193
    task3_regression:
      eta:
        mean_residual: .nan
        n_predictions: 0
        outliers_removed: 193
        std_residual: .nan
      phi:
        mean_residual: .nan
        n_predictions: 0
        outliers_removed: 193
        std_residual: .nan
      qpt:
        mean_residual: -0.04357364634775745
        n_predictions: 193
        outliers_removed: 0
        std_residual: 0.06574756950581842
  baseline_filtered: {}
  rejected_tracks:
    task1_hit_track_assignment:
      average_efficiency: 0.4584943307502424
      average_fake_rate: 0.07356347244680007
      efficiency_std: 0.462644732724397
      fake_rate_std: 0.08478955398442038
      roc_auc: 0.9424878213439098
      total_hits: 7825
      true_assignments: 2405
    task2_track_validity:
      average_efficiency: 0.5
      average_fake_rate: 0.0
      efficiency_std: 0.5
      fake_rate_std: 0.0
      roc_auc: .nan
      total_tracks: 93
      valid_tracks: 93
    task3_regression:
      eta:
        mean_residual: .nan
        n_predictions: 0
        outliers_removed: 93
        std_residual: .nan
      phi:
        mean_residual: .nan
        n_predictions: 0
        outliers_removed: 93
        std_residual: .nan
      qpt:
        mean_residual: -0.03915602161038306
        n_predictions: 93
        outliers_removed: 0
        std_residual: 0.06111904048556017
